name: firebase_model_generator
description: An annotation processor for @FirebaseModel annotations.
version: 0.0.1
author: Lukas Krauch <lukas.krauch@yahoo.de>
homepage: https://github.com/kaskra/firebase_model_generator.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: '0.39.14'
  build: ^1.3.0
  build_config: ^0.4.0
  source_gen: ^0.9.0

dev_dependencies:
  test: ^1.15.4
