name: firebase_model_generator
description: An annotation processor for @FirebaseModel annotations.
version: 0.0.1
author: Lukas Krauch <lukas.krauch@yahoo.de>
homepage: https://github.com/kaskra/firebase_model_generator.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: "0.39.11"
  build: ^1.3.0
  build_config: ^0.4.2
  source_gen: ^0.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
